### ISSUE TITLE
Le package existe-t-il toujours ?

### ISSUE THREAD

**Issue by lycheejp** [trazfr/freebox-exporter#1]
Bonjour,

Impossible d'installer le paquet avec la commande GO : can't load package: package github.com/trazfr/freebox-exporter@latest
go version go1.11.6 linux/amd64

Merci d'avance

**Comment by trazfr** [comment]
Bonjour,

Pour utiliser la commande `go install github.com/trazfr/freebox-exporter@latest`, vous avez besoin de [go1.16](https://golang.org/doc/go1.16#modules). Je vais mettre à jour le README.md pour être plus explicite.
Cette commande clone ce dépôt git et le recompile.

Aujourd'hui la dernière version est 1.16.7:
```bash
$ docker run -ti --rm golang:alpine
/go # go version
go version go1.16.7 linux/amd64
/go # go install github.com/trazfr/freebox-exporter@latest
go: downloading github.com/trazfr/freebox-exporter v0.0.0-20210311213134-e511c8e68ac6
...
/go # freebox-exporter -help
Usage: freebox-exporter [options] <api_token_file>
...
```

Les dépendences nécessitent go1.13, il vous faut mettre à jour. Le package linux/amd64 est disponible sur le site de [golang](https://golang.org/dl/).
J'ai mis à jour le README et `go.mod` pour compiler jusqu'à go1.13. J'avais auparavant mis la version minimale à [go1.16](https://github.com/trazfr/freebox-exporter/blob/e511c8e68ac6a63b85fa8a143c64b717ca79c869/go.mod#L3).


```bash
$ docker run -ti --rm debian
root@6818bbe738d5:/# apt update
root@6818bbe738d5:/# apt -y install curl git
root@6818bbe738d5:/# curl -L -s https://golang.org/dl/go1.13.linux-amd64.tar.gz | tar xz
root@6818bbe738d5:/# /go/bin/go version
go version go1.13 linux/amd64
root@6818bbe738d5:/# GO111MODULE=on /go/bin/go get github.com/trazfr/freebox-exporter@latest
root@6818bbe738d5:/# GO111MODULE=on /go/bin/go install github.com/trazfr/freebox-exporter
root@6818bbe738d5:/# ~/go/bin/freebox-exporter -help
Usage: /root/go/bin/freebox-exporter [options] <api_token_file>
...
```

Bon week-end

**Comment by elipsya** [comment]
Bonjour,
Je suis newbie, et j'essaie, pour prometheus comment l'integrons nous en tant que Target?
merci, désolé

**Comment by trazfr** [comment]
Bonjour,

Je ne vois pas très bien le lien avec la question initiale (problème de compilation).
Néanmoins, votre problème me semble plus être du côté configuration de Prometheus que de cet exporteur.

Je vous renvoie donc à leur documentation qui est bien faite: https://prometheus.io/docs/tutorials/getting_started/.
`freebox-exporter` tient lieu de `node_exporter` dans leur example sachant qu'il écoute par défaut sur `:9091` au lieu de `:9100`, comportement qu'on peut changer via le paramètre `-listen` au démarrage.

Je ferme ce ticket comme je n'ai pas eu de réponse à la question initiale depuis Août 2021 et vous invite à en ouvrir un autre si besoin.

Cdt

**Comment by elipsya** [comment]
Merci, c'est le concept que je n'avais pas, je débute...
Bonne continuation
