### ISSUE TITLE
New metrics

### ISSUE THREAD

**Issue by FabFouge** [trazfr/freebox-exporter#2]
Hello,
Is it possible to have real-time throughput metrics (Download/Upload) ?

**Comment by trazfr** [comment]
Hello,

Yes, if they are available on the Freebox API. But which pieces of info from the Freebox API are you referring to?

There are already a few Prometheus metrics available:

- From [Get a port stats](https://dev.freebox.fr/sdk/os/switch/#get-a-port-stats):
  - `freebox_switch_port_bytes` which is the throughput for each ethernet port with the tags:
    - `dir` == `rx` when the packet is received or `tx` when it is transmitted
    - `id` == identifier of the physical port (1, 2, 3, 4)
    - `state` == `good` or `bad` for `rx`, empty for `tx`
  - `freebox_switch_port_packets` same for the number of packets
- From [Get Wi-Fi Stations List](https://dev.freebox.fr/sdk/os/wifi/#get-wi-fi-stations-list):
  - `freebox_wifi_station_bytes` for the throughput on wifi:
    - `dir` == `rx` or `tx`
    - `id` == the client's MAC address. You may have more info on the client with `freebox_wifi_station_info`

**Comment by FabFouge** [comment]
Hello,
Thanks for your feedback.
I wanted to know if these metrics (indicated in the image) were available

![Metrics](https://user-images.githubusercontent.com/93700003/192256752-b911f25e-e5f3-4a97-821f-edf4f7641472.png)

**Comment by trazfr** [comment]
yes, we may graph those with the [rate()](https://prometheus.io/docs/prometheus/latest/querying/functions/#rate) function on Prometheus.

For example we may have this kind of query (to be changed given the frequency of the scrapes):
- on the wifi: `rate(freebox_wifi_station_bytes[5m])`
- on the switch: `rate(freebox_switch_port_bytes[5m])`, the bandwidth being `freebox_switch_port_bandwidth_bytes`
- on the wlan: `rate(freebox_connection_bytes[5m])`, the bandwidth being `freebox_connection_bandwidth_bytes`

**Comment by FabFouge** [comment]
Hello,
I just got it. It's exactly what I was looking for.
Thank you for your quick and clear response.
Nice day
