### ISSUE TITLE
ERROR : collector.go:348: json: cannot unmarshal object into Go struct field MetricsFreeboxSwitchStatus.result.mac_list of type []*struct { Mac string "json:\"mac\""; Hostname string "json:\"hostname\"" }

### ISSUE THREAD

**Issue by FabFouge** [trazfr/freebox-exporter#3]
Bonjour,

Depuis le passage a la freebox Delta (anciennement pop), j'ai le message d'erreur suivant : 

ERROR : collector.go:348: json: cannot unmarshal object into Go struct field MetricsFreeboxSwitchStatus.result.mac_list of type []*struct { Mac string "json:\"mac\""; Hostname string "json:\"hostname\"" }

Une idée sur le soucis SVP ?

Version du microgiciel: 4.6.4
Version du matériel: Freebox v7 (r1)
Type de connexion: FTTH

**Comment by trazfr** [comment]
Bonjour,

Je ne travaille pas chez Iliad et je développe uniquement sur les données de ma Mini 4k `4.5.8`, et le problème c'est qu'une grosse partie de l'API est non documentée.
Pourriez-vous relancer l'exporteur avec l'option `-debug` svp?

Vous devriez avoir une ligne qui comprend `mac_list` qui ressemble à cela. Pouvez vous me l'envoyer svp? Pour le mettre sur github, obfusquez les `mac` + `hostname`:

```text
DEBUG: 2022/09/30 02:00:08 http_client.go:82: HTTP request: GET /api/v8/switch/status/
DEBUG: 2022/09/30 02:00:08 http_client.go:97: HTTP Result: {"success":true,"result":[{"duplex":"full","mac_list":[{"mac":"XXX","hostname":"XXX"}],"name":"Ethernet 3","link":"up","id":3,"mode":"100BaseTX-FD","speed":"100","rrd_id":"3"},{"duplex":"full","mac_list":[{"mac":"XXX","hostname":"XXX"}],"name":"Ethernet 1","link":"up","id":1,"mode":"1000BaseT-FD","speed":"1000","rrd_id":"1"},{"duplex":"half","name":"Ethernet 2","link":"down","id":2,"mode":"10BaseT-HD","speed":"10","rrd_id":"2"},{"duplex":"half","name":"Ethernet 4","link":"down","id":4,"mode":"10BaseT-HD","speed":"10","rrd_id":"4"}]}
```

Vous pouvez aussi m'envoyer les dumps complets sur quelques minutes à l'adresse mail associée à mon compte pour que je puisse faire des tests si vous ne voulez pas les avoir en public sur github.

**Comment by FabFouge** [comment]
Merci pour votre retour,

Je viens de vous transmettre les infos par mail
